### ISSUE TITLE
Laboratório kubernetes-basics - step 3. Usando ConfigMaps e Secrets

### ISSUE THREAD

**Issue by ralvescosta** [badtuxx/girus-cli#11]
No **Laboratório kubernetes-basics - step 3. Usando ConfigMaps e Secrets**, solicita para criar o sequinte config map

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: k8s-demo
data:
  app.properties: |
    environment=development
    log.level=info
  database.properties: |
    db.host=db.example.com
    db.port=5432
```

e o seguinte pod

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: config-pod
  namespace: k8s-demo
spec:
  containers:
  - name: app
    image: busybox
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: db.user
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: log.level
    volumeMounts:
    - name: config-volume
      mountPath: /config
  volumes:
  - name: config-volume
    configMap:
      name: app-config
```

Como pode ser observado o mapeamento das variaveis do config map nao esta seguindo o formato que o config map esta declarando, quando tenta criar o pod seguindo o manifesto a cima, ocorre o erro

![Image](https://github.com/user-attachments/assets/04809eed-5525-475c-8b63-9ce6f2613daa)

# Steps to reproduce

1- Criar o configmap como solicitado no step 3 do lab
2 - Criar o secret como solicitado no step 3 do lab
3 - Criar o pod como solicitado no setp 3 do lab

# Expected behavior

Criar o pod sem nenhum erro

# Possible Soluction

Acredito que para solucionar o problema ser atualizado o config map para o seguinte manifesto abaixo

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: k8s-demo
data:
  environment: development
  log.level: info
  db.host: db.example.com
  db.port: "5432"
```
